/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package scraper;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FaultyProfile extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FaultyProfile\",\"namespace\":\"scraper\",\"fields\":[{\"name\":\"ResearchInterests\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<java.lang.CharSequence> ResearchInterests;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public FaultyProfile() {}

  /**
   * All-args constructor.
   */
  public FaultyProfile(java.util.List<java.lang.CharSequence> ResearchInterests) {
    this.ResearchInterests = ResearchInterests;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ResearchInterests;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ResearchInterests = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ResearchInterests' field.
   */
  public java.util.List<java.lang.CharSequence> getResearchInterests() {
    return ResearchInterests;
  }

  /**
   * Sets the value of the 'ResearchInterests' field.
   * @param value the value to set.
   */
  public void setResearchInterests(java.util.List<java.lang.CharSequence> value) {
    this.ResearchInterests = value;
  }

  /** Creates a new FaultyProfile RecordBuilder */
  public static scraper.FaultyProfile.Builder newBuilder() {
    return new scraper.FaultyProfile.Builder();
  }
  
  /** Creates a new FaultyProfile RecordBuilder by copying an existing Builder */
  public static scraper.FaultyProfile.Builder newBuilder(scraper.FaultyProfile.Builder other) {
    return new scraper.FaultyProfile.Builder(other);
  }
  
  /** Creates a new FaultyProfile RecordBuilder by copying an existing FaultyProfile instance */
  public static scraper.FaultyProfile.Builder newBuilder(scraper.FaultyProfile other) {
    return new scraper.FaultyProfile.Builder(other);
  }
  
  /**
   * RecordBuilder for FaultyProfile instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FaultyProfile>
    implements org.apache.avro.data.RecordBuilder<FaultyProfile> {

    private java.util.List<java.lang.CharSequence> ResearchInterests;

    /** Creates a new Builder */
    private Builder() {
      super(scraper.FaultyProfile.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(scraper.FaultyProfile.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ResearchInterests)) {
        this.ResearchInterests = data().deepCopy(fields()[0].schema(), other.ResearchInterests);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing FaultyProfile instance */
    private Builder(scraper.FaultyProfile other) {
            super(scraper.FaultyProfile.SCHEMA$);
      if (isValidValue(fields()[0], other.ResearchInterests)) {
        this.ResearchInterests = data().deepCopy(fields()[0].schema(), other.ResearchInterests);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'ResearchInterests' field */
    public java.util.List<java.lang.CharSequence> getResearchInterests() {
      return ResearchInterests;
    }
    
    /** Sets the value of the 'ResearchInterests' field */
    public scraper.FaultyProfile.Builder setResearchInterests(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.ResearchInterests = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'ResearchInterests' field has been set */
    public boolean hasResearchInterests() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'ResearchInterests' field */
    public scraper.FaultyProfile.Builder clearResearchInterests() {
      ResearchInterests = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public FaultyProfile build() {
      try {
        FaultyProfile record = new FaultyProfile();
        record.ResearchInterests = fieldSetFlags()[0] ? this.ResearchInterests : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
